version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  
  webapp:
    container_name: django-app
    restart: always
    build: ./
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  
  worker:
    container_name: celery-worker
    restart: always
    build: .
    volumes:
      - ./:/app
    depends_on:
      - redis
      - webapp
    command: 'celery -A core worker -l info'